### ISSUE TITLE
Regularly dump and backup api_request table

### ISSUE THREAD

**Issue by aepyornis** [skomputer/lilsis#15]

**Comment by skomputer** [comment]
...or just set up an apache request log for api.littlesis.org if it doesn't already exist and ditch api_request forever!

**Comment by aepyornis** [comment]
excellent. that's way better.

**Comment by aepyornis** [comment]
The problem with ditching the api_request table is that it's being used to verify the api_request limit:
https://github.com/littlesis-org/littlesis/blob/master/lib/filter/LsApiRequestFilter.class.php#L54-L71

**Comment by aepyornis** [comment]
but I've setup apache to log the api.littlesis.org, so I'm going to now regularly empty except for those request over the past day. I don't think it's worth it to modify that PHP code right now...eventually we'll move the api to rails.

**Comment by skomputer** [comment]
FYI no api user has ever come near the request limit. so if it's not much more work to stop writing to that table and remove the request limit check than to write a script to clear the table, i'd recommend it...

**Comment by aepyornis** [comment]
hmm. okay, as long as you're cool with removing limits (and a way of keeping track of api requests outside of the apache log) then I can do that. I'm sort of neutral: it's not too difficult to write the dump script either.
