### ISSUE TITLE
Bulk add tool puts the entity ids in wrong order while inserting postition relationships from an org's bulk add page

### ISSUE THREAD

**Issue by aepyornis** [skomputer/lilsis#69]

**Comment by aepyornis** [comment]
also see #66

**Comment by kconn** [comment]
Probably makes sense to allow users to change entity order, and to give some preview of what that means (which then updates based on switch). 
position -- entity a has position at entity b
donation -- entity a gives money to entity b
ownership -- entity a owns entity b
etc
